#!/bin/busybox sh

#argument:
#IMAGEDIR system.img在磁盘上的目录,比如rescue
#SRC  查找host在磁盘上的目录
#ROOT host的磁盘dev，比如/dev/sda1
#MEDIA 系统启动方式 有cd/flash/harddisk/pxe
[ -z $IMAGEFILE ] && IMAGEFILE=superredos-rescue.img
error()
{
        echo $*
        return 1
}

loadmod()
{
	modprobe squashfs
	modprobe loop
	modprobe vfat
	modprobe overlay
}

mkdev()
{
	/lib/systemd/systemd-udevd -d
	udevadm trigger
	udevadm settle
	udevadm control -e
	loadmod
}

try_mount()
{
        RW=$1; shift
        # FIXME: any way to mount ntfs gracefully?
        mount -o $RW $@ || mount.ntfs-3g -o rw,force $@
}

check_root()
{
#        try_mount ro $1 /mnt && [ -e /mnt/$SRC/ramdisk.img ]
#        [ $? -ne 0 ] && return 1
#        zcat /mnt/$SRC/ramdisk.img | cpio -id > /dev/null
        try_mount ro $1 /mnt || return 1
        if [ -e /mnt/$IMAGEDIR/system.sfs ]; then
		mkdir /sqf_sfs
                mount -o loop /mnt/$IMAGEDIR/system.sfs /sqf_sfs
                mount -o loop /sqf_sfs/$IMAGEFILE /sfs
        elif [ -e /mnt/$IMAGEDIR/$IMAGEFILE ]; then
		dd if=/mnt/$IMAGEDIR/$IMAGEFILE of=/$IMAGEFILE bs=4M
                mount -o loop /$IMAGEFILE /sfs
        elif [ -d /mnt/$IMAGEDIR/system ]; then
                remount_rw
                mount --bind /mnt/$IMAGEDIR/system /sfs
        else
#                rm -rf *
                return 1
        fi
#        mkdir cache mnt mnt/sdcard
#        mount -t tmpfs tmpfs cache
        echo " found at $1"
}

remount_rw()
{
        mount -o remount,rw /mnt
}

overwrite_directory()
{
	if [ -d $1 && -d $2 ]; then
		rm -rf $2
		cp -a $1 $2
	fi
}

restore_sys()
{
	rm -rf $1
	rm -rf $2
	cp -a /sfs/etc $1
	cp -a /sfs/root $2
}

set_config()
{
	case $MEDIA in
	cd)
		echo "now to start cd mode"
		;;
	flash|usb)
		echo "now to start flash mode"
		remount_rw
		[ -e /mnt/$SRC/data/etc/firstboot ] || restore_sys /mnt/$SRC/data/etc /mnt/$SRC/data/root
		mount -o bind /mnt/$SRC/data/root /system/root
		mount -o bind /mnt/$SRC/data/etc /system/etc
		;;
	pxe)
		echo "now to start pxe mode"
		;;
	harddisk|*)
		echo "now to start harddisk mode"
		remount_rw
		[ -e /mnt/$SRC/data/etc/firstboot ] || restore_sys /mnt/$SRC/data/etc /mnt/$SRC/data/root
		mount -o bind /mnt/$SRC/data/root /system/root
		mount -o bind /mnt/$SRC/data/etc /system/etc
		;;
	esac
	mount -o bind /mnt/$SRC /system/host
}
#SRC=BOOT
#ROOT=/dev/sda1
LOG=/dev/null
[ -e $LOG ] || busybox mknod $LOG c 1 3

#exec 2> $LOG
#/bin/sh
[ -e /tmpfs ] || /bin/busybox mkdir /tmpfs
[ -e /dev   ] || /bin/busybox mkdir /dev
[ -e /sys   ] || /bin/busybox mkdir /sys
[ -e /proc  ] || /bin/busybox mkdir /proc
[ -e /system ] || /bin/busybox mkdir /system
[ -e /sfs ] || /bin/busybox mkdir /sfs
[ -e /mnt ] || /bin/busybox mkdir /mnt

busybox mount -t proc proc /proc
busybox mount -t devtmpfs devtmpfs /dev 
#busybox mount -t tmpfs mdev /dev 
busybox mount -t sysfs sys /sys

busybox --install -s

#echo /bin/mdev > /proc/sys/kernel/hotplug
#export PATH=$PATH:/system/bin
export PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
echo 0 0 0 0 > /proc/sys/kernel/printk

#echo Mounting root file system...

mdev -s
#mkdev

#echo "src=$SRC"
#echo "root=$ROOT"
#/bin/busybox sh

mount -o loop /opt/rootfs.sqf /sfs

#while [ 1 ]; do
#        for device in $ROOT /dev/sr* /dev/sd* /dev/nvme* /dev/vd* /dev/cdrom; do
#		echo $device
#                check_root $device && break 2
#                mountpoint -q /mnt && umount /mnt
#        done
#        sleep 1
#        echo -n .
#done
#umount /mnt

#remount_rw
#echo "mount overlayfs /system"

mount -t tmpfs tmpfs /system
cp -a /sfs/* /system

#mount -t tmpfs tmpfs /tmpfs
#mkdir /tmpfs/upperdir /tmpfs/workdir
#mount -t overlay overlay -o lowerdir=/sfs,upperdir=/tmpfs/upperdir,workdir=/tmpfs/workdir /system

#set_config

#[ -e /mnt/$SRC/data/etc/firstboot ] || restore_sys /mnt/$SRC/data/etc /mnt/$SRC/data/root
#mount -o bind /mnt/$SRC /system/host
#mount -o bind /mnt/$SRC/data/root /system/root
#mount -o bind /mnt/$SRC/data/etc /system/etc

#echo "harddisk=$harddisk"
#mkdir -p /system/media/$harddisk
#mount --move /mnt /system/media/$harddisk
#echo "run rootfs init"
exec switch_root /system /sbin/init

sh # avoid kernel panic
